server:
  port: 8000
spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
fly:
  security:
    no-auth-urls:
      - /greet/**
      - /authentication/**
      - /doc.html

debug: true
logging:
  level:
    org.springframework.security:
      TRACE
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
