server:
  port: 8000
spring:
  application:
    name: fly-kit
  profiles:
    active: dev
  docker:
    compose:
      readiness:
        tcp:
          connect-timeout: 10s
          read-timeout: 5s
      enabled: true
      file: "compose.yaml"

  jackson:
    default-property-inclusion: non_null
mybatis-plus:
  type-aliases-package: com.duofan.fly.core.base.entity
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: order
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.duofan.fly.web.starter
fly:
  security:
    login:
      is-remember-parameter: remember
