server:
  port: 8000


spring:
  application:
    name: fly-kit
  profiles:
    active: dev
  docker:
    compose:
      readiness:
        tcp:
          connect-timeout: 10s
          read-timeout: 5s
      enabled: true
      file: "compose.yaml"


mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true


