server:
  port: 8000
spring:
  application:
    name: fly-kit
  profiles:
    active: dev
  docker:
    compose:
      readiness:
        tcp:
          connect-timeout: 10s
          read-timeout: 5s
      enabled: true
      file: "compose.yaml"

  jackson:
    default-property-inclusion: non_null
mybatis-plus:
  type-aliases-package: com.duofan.fly.core.base.entity
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
