server:
  port: 8000


spring:
  application:
    name: fly-kit
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: kit-db
    password: mzEM2St3DFsSmeRs
    url: jdbc:mysql://localhost:3306/kit-db?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false
  profiles:
    active: dev
  docker:
    compose:
      readiness:
        tcp:
          connect-timeout: 10s
          read-timeout: 5s
      enabled: true
      file: "compose.yaml"
  data:
    redis:
      password:
      host: 127.0.0.1
      port: 6379
  security:
    user:
      password: root
      name: root
      roles: ADMIN
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    #operations-sorter: order
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.duofan.fly.web.starter
  default-flat-param-object: true

knife4j:
  enable: true
  setting:
    language: zh_cn
    swagger-model-name: 实体类列表
#  documents:
#    - name: 标题1
#      locations: classpath:markdown/*
#      group: default

  basic:
    enable: false
    username: abc
    password: 123
