server:
  port: 8000
spring:
  application:
    name: fly-kit-dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: kit-db
    password: mzEM2St3DFsSmeRs
    url: jdbc:mysql://localhost:3306/kit-db?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
  data:
    redis:
      password:
      host: 127.0.0.1
      port: 6379
    #  security:
    #    user:
    #      password: root
    #      name: root
    #      roles: ADMIN
    #springdoc:
    #  swagger-ui:
    #    path: /swagger-ui.html
    #    tags-sorter: alpha
    #operations-sorter: order
  #  api-docs:
  #    path: /v3/api-docs
  #  group-configs:
  #    - group: 'default'
  #      paths-to-match: '/**'
  #      packages-to-scan: com.duofan.fly.web.starter
  #    - group: 'fly'
  #      paths-to-match: '/**'
  #      packages-to-scan: com.duofan.fly.manage.api.controller.v1
#  devtools:
#    livereload:
#      enabled: false
#  default-flat-param-object: true


debug: false
logging:
  level:
    org.springframework.security:
      TRACE
knife4j:
  enable: true
  setting:
    language: zh_cn
    swagger-model-name: 实体类列表
  documents:
    - name: 标题1
      locations: classpath:markdown/*
      group: default

  basic:
    enable: false
    username: abc
    password: 123
fly:
  security:
    captcha-enabled: true
  jpa:
    ddl-auto:
      enabled: true
