services:
#  redis:
#    image: "redis:alpine"
#    ports:
#      - '6397'
  database:
    image: "mysql"
    ports:
      - '3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ALLOW_EMPTY_PASSWORD: root
      MYSQL_DATABASE: kit-db
